# Development environment for paquo
name: paquo

channels:
  - conda-forge
  - sdvillal
  - defaults

dependencies:
  - python>=3.6.1
  - pip
  - jpype1>=1.0.1
  - shapely
  - qupath
  - pytest>=6
  - pytest-cov
  - pip:
    - dynaconf>=3,!=3.1.0
    - "-e ."
