# Development environment for paquo
name: paquo

channels:
  - conda-forge
  - sdvillal
  - defaults

dependencies:
  - python=3.8
  - pip
  - jpype1>=1.0.1
  - pytest
  - qupath
  # - python-openslide
  - shapely
  - pytest
  - pip:
    - "-e ."
