name: static type analysis

on: [push, pull_request]

jobs:
  build:
    name: paquo mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -e .[dev]
      - name: Run mypy
        run: |
          mypy paquo
